### PR TITLE
Add .gitignore file to avoid committing compiled objects

### PR DESCRIPTION
**Pull request by dualspiral**
Some of these files are build artifacts and should not be committed. Added .gitignore file to prevent such commits in a future.

### CODE REVIEW

**Comment by dualspiral** [comment]
Before pulling this, I would check that the files do get auto regenerated - but in general, anything in a /build folder shouldn't be pushed.

**Comment by robe16** [comment]
Brill - this is why I needed somebody experienced to help me!!
I assume by accepting your commit, it will update on my working file on Mac when i pull it.

**Comment by dualspiral** [comment]
It should do. You'll need to "git pull" to get it. You can test it first by using "git fetch" then "git checkout origin/gitignore".

**Comment by robe16** [comment]
Honestly, you've lost me on that one. I'm using Android Studio and used the VCS Push function to upload it all to github. There is a VCS Pull as well, which I assume should pull the latest versions onto my laptop? I tried this way but I can't see the .gitignore file in the build folder when in browser - I assume it should have?

**Comment by dualspiral** [comment]
No, it's not on master yet, I put it a branch for you to review. Is there a "fetch" function and a "checkout/switch branch" function? If so, fetch (if not, pull), then switch to "origin/gitignore". You'll see this code then for review.

Once you are done, switch back to "master", merge this request, then pull once more.

**Comment by dualspiral** [comment]
You might also like to go through https://try.github.io/ - it's a really good resource for using Git.

**Comment by robe16** [comment]
ah, i see - I'll take a look now.

**Pull request merged**
